### ISSUE TITLE
zoomable class set on wrong div

### ISSUE THREAD

**Issue by nielsrune** [Ecodev/natural-gallery-js#7] opened 2018-03-30 19:54 UTC
I found this project very useful for a simple showcase site and it looks very promising!

However, after basically having adapted the standard demo, it seems the documentation in the Readme needs to be updated, at least the options and events section. Some of the options are not mentioned and some options overrides other options.

As I could not get my local demo to zoom and rotate on hover, I looked in the source files while analyzing the output in chrome dev tools.

Accordingly, there seems to be an issue with the class `zoomable` being set on the wrong `div`.

The `zoomable` class must be set on the `div` having the `rotation`, ie. the `div` containing the image url in its `style` attribute:
https://github.com/Ecodev/natural-gallery-js/blob/9d5e1cc867f3d269a30c1ad605c9f2222e87b30c/app/js/Item.ts#L184-L186

In current version 2.7.4 the `zoomable` class is added to the parent `div`, the one with the classes `figure loaded visible`. After a live manipulation with chrome dev tools switching where the `zoomable` class is added, the hover effect is working as expected.

I'm not fully aware how to build a new dist from the sources, so unfortunately no pull request from my side on this one. Hoping for a fix, though :-)

**Comment by sambaptista** [comment] 2018-03-31 08:39
Hello, thank you for your feedback. 

Have you activated the lightbox option ? In fact, the rotation is decorative and applies when there is a zoom. 

But the zoom itself is not decorative, it has a semantic meaning for when the click on the image will really zoom (in the lightbox). 

For sure, it's not explained in the docs, and should be.

**Comment by nielsrune** [comment] 2018-03-31 23:05
Yes, I'm having `lightbox: true`.

Forgive me if not understanding your reply correctly. The thing not working for me with my local copy of the demo, but with the v2.7.4 natural-gallery-full.js from yarn is the little zoom and rotate on hovering an image outside the lightbox.

Since filing the issue, I managed to make a quick build with `Utility.addClass(image, 'rotation zoomable');` in line 185 of Item.ts. This gives the expected behavior like on the demo hosted at https://ecodev.ch/natural-gallery/demo/

**Comment by sambaptista** [comment] 2018-04-02 08:53
I can't reproduce. Can you share your setup?

**Comment by nielsrune** [comment] 2018-04-02 18:46
Strange. Setup is apache2 running on a Raspberry Pi with Raspbian.
On Chrome 65 as well as Firefox 59 on my Fedora 27 machine, the issue is persistent. Same on Chrome on my Nexus 5 Android phone.

I have set up to versions of the standard demo: [upstream] and [patched]

Upstream is using the .js v2.7.4 from yarn. No rotation or zoom on hover.
Patched is using my own build. This gives me the expected behavior with rotation and zoom on hover.

In the patched .js line 185 of app/js/Item.ts was changed to: `Utility.addClass(image, 'rotation zoomable');` and built with `npm run full`.

Both having zoomRotation set to true, of course.

[upstream]: https://pengekat.dk/upstream.html
[patched]: https://pengekat.dk/patched.html

**Comment by sambaptista** [comment] 2018-04-03 09:17
Ok I could reproduce, but I have to check deeply the cause of this bug. 

I use this library in a big project and the zoom works fine with this version, so I have to be sure before changing that class. 

Will be fixed soon.

**Comment by sambaptista** [comment] 2018-04-06 11:09
I've just pushed a fix. 

The patch you suggest ignores the case where lightbox = false, and there is no zoom on click. The class "zoom" should not be applied unconditionally.

The bug happened when there is no "button" on thumbnails (it's your case : you have a label).

Enjoy.

**Closed by sambaptista** 2018-04-06 11:09 UTC
Labels: todo
